[package]
name = "yyts"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.9.2"
dirs = "6.0.0"
serde_json = "1.0.145"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "benchmark"
harness = false
path = "benches/benchmark.rs"
